spring:
  datasource:
    url: jdbc:h2:mem:testdb  # URL in-memory, nombre fijo para facilitar acceso
    driver-class-name: org.h2.Driver
    username: sa  # Usuario por defecto
    password: ""  # Contraseña vacía (puedes definir una si prefieres)
  h2:
    console:
      enabled: true  # Habilita la consola web
      path: /h2-console  # Ruta de acceso (opcional, por defecto es esta)
      settings:
        trace: false  # Opcional: desactiva trace para menos logs
        web-allow-others: false  # Opcional: restringe acceso a localhost
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  # O create-drop para tests
    show-sql: true  # Opcional: muestra SQL en logs para depuración